os:
  - osx
language: cpp
before_install:
  - brew update
  - brew upgrade libtool
  - brew install libgcrypt
  - echo $PATH
  - which libtool
script:
  - ./configure --prefix="$PWD/root/openocd"
  - make
  - make install
