os:
  - osx
language: cpp
before_install:
  - brew update
  - brew upgrade libtool boost
  - brew install libgcrypt
script:
  - export LIBTOOL=glibtool
  - ./configure --prefix="$PWD/root"
  - make
  - make install
  - find root/.
